name: party
description: Flutter project
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  awesome_bottom_bar: ^1.2.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  google_fonts: ^5.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.4
  build_runner: ^2.4.4
  

flutter:
  uses-material-design: true
